Dynamic extraction of Manifest Data
rdagumampan/yuniql pull request #212
Opened 2021-08-27 21:00 UTC by black-eagle17

Greetings,
     I am new to open source development and programming overall. I managed to get the manifest data printing using the derivation technique suggested. However, I am having a little trouble figuring out how I would iterate through the list of supported platforms to get all of them to print. I hope you can review my code and give me pointers/feedback so I can learn from my mistakes.

2021-08-28 04:06 UTC, rdagumampan commented
Hi @black-eagle17 , thank you very much for you contribution. Every contribution counts, so we highly appreciate it. For your question, you can try `Reflection` if you can extract all implementations of `IDataService` and create dynamic instance of the classes. You can also use `SUPPORTED_DATABASES` enums as keys to find the implementations faster. HT/Rodel

2021-08-29 02:39 UTC, black-eagle17 commented
Thank you for the feedback, I read up on reflection and it is now implemented in the code. I think I am ready for a PR review.

2021-09-06 19:16 UTC, rdagumampan commented
Thank you very much @black-eagle17. I am reviewing your PR now but may take a while. There were many changes that doesnt seem to be reall change, maybe just some encoding differences. I will try to do Beyond Compare of the two branches and see the actual text change.

2021-09-09 00:53 UTC, black-eagle17 commented
@rdagumampan Thank you, any suggestions on how I could ensure a consistent encoding. I'm on Linux so it might be how I checkout my line endings.

2021-09-09 03:50 UTC, rdagumampan commented
Hi @black-eagle17 , i think its the encoding. When using Beyond Compare, all of your changes looks ok. I think I can pull this change over after I hear back from you on the other comments.

![image](https://user-images.githubusercontent.com/5895952/132619426-2f2288e8-7aa8-4ede-9ecd-7c724df7ac75.png)

2021-09-09 05:04 UTC, rdagumampan requested changes
See me comments below.

2021-09-09 05:04 UTC, rdagumampan commented on yuniql-cli/CommandLineService.cs
> +                        _manifestData.printData();
Lets move the logic of this into the `CommandLineService` so this class remains just plain object without any behavior. How we format into the output stream would be responsibility of the CLI classes.

2021-12-20 13:55 UTC, merged